/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Isbm2RestClient.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Isbm2RestClient.Model
{
    /// <summary>
    /// OpenSubscriptionSession400Response
    /// </summary>
    [JsonConverter(typeof(OpenSubscriptionSession400ResponseJsonConverter))]
    [DataContract(Name = "openSubscriptionSession_400_response")]
    public partial class OpenSubscriptionSession400Response : AbstractOpenAPISchema, IEquatable<OpenSubscriptionSession400Response>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OpenSubscriptionSession400Response" /> class
        /// with the <see cref="ParameterFault" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ParameterFault.</param>
        public OpenSubscriptionSession400Response(ParameterFault actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OpenSubscriptionSession400Response" /> class
        /// with the <see cref="NamespaceFault" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of NamespaceFault.</param>
        public OpenSubscriptionSession400Response(NamespaceFault actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(NamespaceFault))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ParameterFault))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: NamespaceFault, ParameterFault");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `ParameterFault`. If the actual instance is not `ParameterFault`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ParameterFault</returns>
        public ParameterFault GetParameterFault()
        {
            return (ParameterFault)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `NamespaceFault`. If the actual instance is not `NamespaceFault`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of NamespaceFault</returns>
        public NamespaceFault GetNamespaceFault()
        {
            return (NamespaceFault)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OpenSubscriptionSession400Response {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, OpenSubscriptionSession400Response.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of OpenSubscriptionSession400Response
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of OpenSubscriptionSession400Response</returns>
        public static OpenSubscriptionSession400Response FromJson(string jsonString)
        {
            OpenSubscriptionSession400Response newOpenSubscriptionSession400Response = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newOpenSubscriptionSession400Response;
            }

            try
            {
                newOpenSubscriptionSession400Response = new OpenSubscriptionSession400Response(JsonConvert.DeserializeObject<NamespaceFault>(jsonString, OpenSubscriptionSession400Response.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newOpenSubscriptionSession400Response;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into NamespaceFault: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newOpenSubscriptionSession400Response = new OpenSubscriptionSession400Response(JsonConvert.DeserializeObject<ParameterFault>(jsonString, OpenSubscriptionSession400Response.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newOpenSubscriptionSession400Response;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ParameterFault: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OpenSubscriptionSession400Response);
        }

        /// <summary>
        /// Returns true if OpenSubscriptionSession400Response instances are equal
        /// </summary>
        /// <param name="input">Instance of OpenSubscriptionSession400Response to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OpenSubscriptionSession400Response input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for OpenSubscriptionSession400Response
    /// </summary>
    public class OpenSubscriptionSession400ResponseJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(OpenSubscriptionSession400Response).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return OpenSubscriptionSession400Response.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
