/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Isbm2RestClient.Client.OpenAPIDateConverter;

namespace Isbm2RestClient.Model
{
    /// <summary>
    /// Defines SessionType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SessionType
    {
        /// <summary>
        /// Enum PublicationProvider for value: PublicationProvider
        /// </summary>
        [EnumMember(Value = "PublicationProvider")]
        PublicationProvider = 1,

        /// <summary>
        /// Enum PublicationConsumer for value: PublicationConsumer
        /// </summary>
        [EnumMember(Value = "PublicationConsumer")]
        PublicationConsumer = 2,

        /// <summary>
        /// Enum RequestProvider for value: RequestProvider
        /// </summary>
        [EnumMember(Value = "RequestProvider")]
        RequestProvider = 3,

        /// <summary>
        /// Enum RequestConsumer for value: RequestConsumer
        /// </summary>
        [EnumMember(Value = "RequestConsumer")]
        RequestConsumer = 4

    }

}
