/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Isbm2RestClient.Api;
using Isbm2RestClient.Model;
using Isbm2RestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Isbm2RestClient.Test.Model
{
    /// <summary>
    ///  Class for testing AuthenticationScheme
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuthenticationSchemeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuthenticationScheme
        //private AuthenticationScheme instance;

        public AuthenticationSchemeTests()
        {
            // TODO uncomment below to create an instance of AuthenticationScheme
            //instance = new AuthenticationScheme();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthenticationScheme
        /// </summary>
        [Fact]
        public void AuthenticationSchemeInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuthenticationScheme
            //Assert.IsType<AuthenticationScheme>(instance);
        }


        /// <summary>
        /// Test the property 'SchemeName'
        /// </summary>
        [Fact]
        public void SchemeNameTest()
        {
            // TODO unit test for the property 'SchemeName'
        }
        /// <summary>
        /// Test the property 'SchemeInfoUrl'
        /// </summary>
        [Fact]
        public void SchemeInfoUrlTest()
        {
            // TODO unit test for the property 'SchemeInfoUrl'
        }

    }

}
