/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Isbm2RestClient.Api;
using Isbm2RestClient.Model;
using Isbm2RestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Isbm2RestClient.Test.Model
{
    /// <summary>
    ///  Class for testing Channel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Channel
        //private Channel instance;

        public ChannelTests()
        {
            // TODO uncomment below to create an instance of Channel
            //instance = new Channel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Channel
        /// </summary>
        [Fact]
        public void ChannelInstanceTest()
        {
            // TODO uncomment below to test "IsType" Channel
            //Assert.IsType<Channel>(instance);
        }


        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'ChannelType'
        /// </summary>
        [Fact]
        public void ChannelTypeTest()
        {
            // TODO unit test for the property 'ChannelType'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'SecurityTokens'
        /// </summary>
        [Fact]
        public void SecurityTokensTest()
        {
            // TODO unit test for the property 'SecurityTokens'
        }

    }

}
