/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Isbm2RestClient.Api;
using Isbm2RestClient.Model;
using Isbm2RestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Isbm2RestClient.Test.Model
{
    /// <summary>
    ///  Class for testing ChannelType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChannelType
        //private ChannelType instance;

        public ChannelTypeTests()
        {
            // TODO uncomment below to create an instance of ChannelType
            //instance = new ChannelType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelType
        /// </summary>
        [Fact]
        public void ChannelTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChannelType
            //Assert.IsType<ChannelType>(instance);
        }



    }

}
