/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Isbm2RestClient.Api;
using Isbm2RestClient.Model;
using Isbm2RestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Isbm2RestClient.Test.Model
{
    /// <summary>
    ///  Class for testing ContentFilteringLanguage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContentFilteringLanguageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContentFilteringLanguage
        //private ContentFilteringLanguage instance;

        public ContentFilteringLanguageTests()
        {
            // TODO uncomment below to create an instance of ContentFilteringLanguage
            //instance = new ContentFilteringLanguage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContentFilteringLanguage
        /// </summary>
        [Fact]
        public void ContentFilteringLanguageInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContentFilteringLanguage
            //Assert.IsType<ContentFilteringLanguage>(instance);
        }


        /// <summary>
        /// Test the property 'ApplicableMediaTypes'
        /// </summary>
        [Fact]
        public void ApplicableMediaTypesTest()
        {
            // TODO unit test for the property 'ApplicableMediaTypes'
        }
        /// <summary>
        /// Test the property 'LanguageName'
        /// </summary>
        [Fact]
        public void LanguageNameTest()
        {
            // TODO unit test for the property 'LanguageName'
        }
        /// <summary>
        /// Test the property 'LanguageVersion'
        /// </summary>
        [Fact]
        public void LanguageVersionTest()
        {
            // TODO unit test for the property 'LanguageVersion'
        }

    }

}
