/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Isbm2RestClient.Api;
using Isbm2RestClient.Model;
using Isbm2RestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Isbm2RestClient.Test.Model
{
    /// <summary>
    ///  Class for testing FilterExpressionExpressionString
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FilterExpressionExpressionStringTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FilterExpressionExpressionString
        //private FilterExpressionExpressionString instance;

        public FilterExpressionExpressionStringTests()
        {
            // TODO uncomment below to create an instance of FilterExpressionExpressionString
            //instance = new FilterExpressionExpressionString();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FilterExpressionExpressionString
        /// </summary>
        [Fact]
        public void FilterExpressionExpressionStringInstanceTest()
        {
            // TODO uncomment below to test "IsType" FilterExpressionExpressionString
            //Assert.IsType<FilterExpressionExpressionString>(instance);
        }


        /// <summary>
        /// Test the property 'Expression'
        /// </summary>
        [Fact]
        public void ExpressionTest()
        {
            // TODO unit test for the property 'Expression'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'LanguageVersion'
        /// </summary>
        [Fact]
        public void LanguageVersionTest()
        {
            // TODO unit test for the property 'LanguageVersion'
        }

    }

}
