/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Isbm2RestClient.Api;
using Isbm2RestClient.Model;
using Isbm2RestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Isbm2RestClient.Test.Model
{
    /// <summary>
    ///  Class for testing FilterExpression
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FilterExpressionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FilterExpression
        //private FilterExpression instance;

        public FilterExpressionTests()
        {
            // TODO uncomment below to create an instance of FilterExpression
            //instance = new FilterExpression();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FilterExpression
        /// </summary>
        [Fact]
        public void FilterExpressionInstanceTest()
        {
            // TODO uncomment below to test "IsType" FilterExpression
            //Assert.IsType<FilterExpression>(instance);
        }


        /// <summary>
        /// Test the property 'ApplicableMediaTypes'
        /// </summary>
        [Fact]
        public void ApplicableMediaTypesTest()
        {
            // TODO unit test for the property 'ApplicableMediaTypes'
        }
        /// <summary>
        /// Test the property 'ExpressionString'
        /// </summary>
        [Fact]
        public void ExpressionStringTest()
        {
            // TODO unit test for the property 'ExpressionString'
        }
        /// <summary>
        /// Test the property 'Namespaces'
        /// </summary>
        [Fact]
        public void NamespacesTest()
        {
            // TODO unit test for the property 'Namespaces'
        }

    }

}
