/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Isbm2RestClient.Api;
using Isbm2RestClient.Model;
using Isbm2RestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Isbm2RestClient.Test.Model
{
    /// <summary>
    ///  Class for testing Namespace
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NamespaceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Namespace
        //private Namespace instance;

        public NamespaceTests()
        {
            // TODO uncomment below to create an instance of Namespace
            //instance = new Namespace();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Namespace
        /// </summary>
        [Fact]
        public void NamespaceInstanceTest()
        {
            // TODO uncomment below to test "IsType" Namespace
            //Assert.IsType<Namespace>(instance);
        }


        /// <summary>
        /// Test the property 'Prefix'
        /// </summary>
        [Fact]
        public void PrefixTest()
        {
            // TODO unit test for the property 'Prefix'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
