/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Isbm2RestClient.Api;
using Isbm2RestClient.Model;
using Isbm2RestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Isbm2RestClient.Test.Model
{
    /// <summary>
    ///  Class for testing SecurityDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SecurityDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SecurityDetails
        //private SecurityDetails instance;

        public SecurityDetailsTests()
        {
            // TODO uncomment below to create an instance of SecurityDetails
            //instance = new SecurityDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecurityDetails
        /// </summary>
        [Fact]
        public void SecurityDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SecurityDetails
            //Assert.IsType<SecurityDetails>(instance);
        }


        /// <summary>
        /// Test the property 'IsTLSEnabled'
        /// </summary>
        [Fact]
        public void IsTLSEnabledTest()
        {
            // TODO unit test for the property 'IsTLSEnabled'
        }
        /// <summary>
        /// Test the property 'IsSecurityTokenRequired'
        /// </summary>
        [Fact]
        public void IsSecurityTokenRequiredTest()
        {
            // TODO unit test for the property 'IsSecurityTokenRequired'
        }
        /// <summary>
        /// Test the property 'IsSecurityTokenEncryptionEnabled'
        /// </summary>
        [Fact]
        public void IsSecurityTokenEncryptionEnabledTest()
        {
            // TODO unit test for the property 'IsSecurityTokenEncryptionEnabled'
        }
        /// <summary>
        /// Test the property 'IsCertificateRequired'
        /// </summary>
        [Fact]
        public void IsCertificateRequiredTest()
        {
            // TODO unit test for the property 'IsCertificateRequired'
        }
        /// <summary>
        /// Test the property 'IsRBACEnabled'
        /// </summary>
        [Fact]
        public void IsRBACEnabledTest()
        {
            // TODO unit test for the property 'IsRBACEnabled'
        }
        /// <summary>
        /// Test the property 'IsKeyManagementServiceEnabled'
        /// </summary>
        [Fact]
        public void IsKeyManagementServiceEnabledTest()
        {
            // TODO unit test for the property 'IsKeyManagementServiceEnabled'
        }
        /// <summary>
        /// Test the property 'IsEndToEndMessageEncryptionEnabled'
        /// </summary>
        [Fact]
        public void IsEndToEndMessageEncryptionEnabledTest()
        {
            // TODO unit test for the property 'IsEndToEndMessageEncryptionEnabled'
        }

    }

}
