/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Isbm2RestClient.Api;
using Isbm2RestClient.Model;
using Isbm2RestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Isbm2RestClient.Test.Model
{
    /// <summary>
    ///  Class for testing Session
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SessionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Session
        //private Session instance;

        public SessionTests()
        {
            // TODO uncomment below to create an instance of Session
            //instance = new Session();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Session
        /// </summary>
        [Fact]
        public void SessionInstanceTest()
        {
            // TODO uncomment below to test "IsType" Session
            //Assert.IsType<Session>(instance);
        }


        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Fact]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }
        /// <summary>
        /// Test the property 'SessionType'
        /// </summary>
        [Fact]
        public void SessionTypeTest()
        {
            // TODO unit test for the property 'SessionType'
        }
        /// <summary>
        /// Test the property 'ListenerUrl'
        /// </summary>
        [Fact]
        public void ListenerUrlTest()
        {
            // TODO unit test for the property 'ListenerUrl'
        }
        /// <summary>
        /// Test the property 'Topics'
        /// </summary>
        [Fact]
        public void TopicsTest()
        {
            // TODO unit test for the property 'Topics'
        }
        /// <summary>
        /// Test the property 'FilterExpressions'
        /// </summary>
        [Fact]
        public void FilterExpressionsTest()
        {
            // TODO unit test for the property 'FilterExpressions'
        }

    }

}
