/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Isbm2RestClient.Api;
using Isbm2RestClient.Model;
using Isbm2RestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Isbm2RestClient.Test.Model
{
    /// <summary>
    ///  Class for testing SessionFault
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SessionFaultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SessionFault
        //private SessionFault instance;

        public SessionFaultTests()
        {
            // TODO uncomment below to create an instance of SessionFault
            //instance = new SessionFault();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SessionFault
        /// </summary>
        [Fact]
        public void SessionFaultInstanceTest()
        {
            // TODO uncomment below to test "IsType" SessionFault
            //Assert.IsType<SessionFault>(instance);
        }


        /// <summary>
        /// Test the property 'Fault'
        /// </summary>
        [Fact]
        public void FaultTest()
        {
            // TODO unit test for the property 'Fault'
        }

    }

}
