/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Isbm2RestClient.Api;
using Isbm2RestClient.Model;
using Isbm2RestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Isbm2RestClient.Test.Model
{
    /// <summary>
    ///  Class for testing SupportedOperationsSupportedAuthentications
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SupportedOperationsSupportedAuthenticationsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SupportedOperationsSupportedAuthentications
        //private SupportedOperationsSupportedAuthentications instance;

        public SupportedOperationsSupportedAuthenticationsTests()
        {
            // TODO uncomment below to create an instance of SupportedOperationsSupportedAuthentications
            //instance = new SupportedOperationsSupportedAuthentications();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SupportedOperationsSupportedAuthentications
        /// </summary>
        [Fact]
        public void SupportedOperationsSupportedAuthenticationsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SupportedOperationsSupportedAuthentications
            //Assert.IsType<SupportedOperationsSupportedAuthentications>(instance);
        }


        /// <summary>
        /// Test the property 'SoapSupportedTokenSchemas'
        /// </summary>
        [Fact]
        public void SoapSupportedTokenSchemasTest()
        {
            // TODO unit test for the property 'SoapSupportedTokenSchemas'
        }
        /// <summary>
        /// Test the property 'RestSupportedAuthenticationSchemes'
        /// </summary>
        [Fact]
        public void RestSupportedAuthenticationSchemesTest()
        {
            // TODO unit test for the property 'RestSupportedAuthenticationSchemes'
        }

    }

}
