/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Isbm2RestClient.Api;
using Isbm2RestClient.Model;
using Isbm2RestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Isbm2RestClient.Test.Model
{
    /// <summary>
    ///  Class for testing SupportedOperations
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SupportedOperationsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SupportedOperations
        //private SupportedOperations instance;

        public SupportedOperationsTests()
        {
            // TODO uncomment below to create an instance of SupportedOperations
            //instance = new SupportedOperations();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SupportedOperations
        /// </summary>
        [Fact]
        public void SupportedOperationsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SupportedOperations
            //Assert.IsType<SupportedOperations>(instance);
        }


        /// <summary>
        /// Test the property 'IsXMLFilteringEnabled'
        /// </summary>
        [Fact]
        public void IsXMLFilteringEnabledTest()
        {
            // TODO unit test for the property 'IsXMLFilteringEnabled'
        }
        /// <summary>
        /// Test the property 'IsJSONFilteringEnabled'
        /// </summary>
        [Fact]
        public void IsJSONFilteringEnabledTest()
        {
            // TODO unit test for the property 'IsJSONFilteringEnabled'
        }
        /// <summary>
        /// Test the property 'SupportedContentFilteringLanguages'
        /// </summary>
        [Fact]
        public void SupportedContentFilteringLanguagesTest()
        {
            // TODO unit test for the property 'SupportedContentFilteringLanguages'
        }
        /// <summary>
        /// Test the property 'SupportedAuthentications'
        /// </summary>
        [Fact]
        public void SupportedAuthenticationsTest()
        {
            // TODO unit test for the property 'SupportedAuthentications'
        }
        /// <summary>
        /// Test the property 'SecurityLevelConformance'
        /// </summary>
        [Fact]
        public void SecurityLevelConformanceTest()
        {
            // TODO unit test for the property 'SecurityLevelConformance'
        }
        /// <summary>
        /// Test the property 'IsDeadLetteringEnabled'
        /// </summary>
        [Fact]
        public void IsDeadLetteringEnabledTest()
        {
            // TODO unit test for the property 'IsDeadLetteringEnabled'
        }
        /// <summary>
        /// Test the property 'IsChannelCreationEnabled'
        /// </summary>
        [Fact]
        public void IsChannelCreationEnabledTest()
        {
            // TODO unit test for the property 'IsChannelCreationEnabled'
        }
        /// <summary>
        /// Test the property 'IsOpenChannelSecuringEnabled'
        /// </summary>
        [Fact]
        public void IsOpenChannelSecuringEnabledTest()
        {
            // TODO unit test for the property 'IsOpenChannelSecuringEnabled'
        }
        /// <summary>
        /// Test the property 'IsWhitelistRequired'
        /// </summary>
        [Fact]
        public void IsWhitelistRequiredTest()
        {
            // TODO unit test for the property 'IsWhitelistRequired'
        }
        /// <summary>
        /// Test the property 'DefaultExpiryDuration'
        /// </summary>
        [Fact]
        public void DefaultExpiryDurationTest()
        {
            // TODO unit test for the property 'DefaultExpiryDuration'
        }
        /// <summary>
        /// Test the property 'AdditionalInformationURL'
        /// </summary>
        [Fact]
        public void AdditionalInformationURLTest()
        {
            // TODO unit test for the property 'AdditionalInformationURL'
        }

    }

}
