/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Isbm2RestClient.Client;
using Isbm2RestClient.Model;

namespace Isbm2RestClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IChannelManagementApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Adds security tokens to a channel.
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="requestBody">The SecurityTokens to add. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void AddSecurityTokens(string channelUri, List<Dictionary<String, Object>>? requestBody = default(List<Dictionary<String, Object>>?), int operationIndex = 0);

        /// <summary>
        /// Adds security tokens to a channel.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="requestBody">The SecurityTokens to add. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> AddSecurityTokensWithHttpInfo(string channelUri, List<Dictionary<String, Object>>? requestBody = default(List<Dictionary<String, Object>>?), int operationIndex = 0);
        /// <summary>
        /// Create a new channel with the specified URI path fragment.
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channel">The Channel to create (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Channel</returns>
        Channel CreateChannel(Channel? channel = default(Channel?), int operationIndex = 0);

        /// <summary>
        /// Create a new channel with the specified URI path fragment.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channel">The Channel to create (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Channel</returns>
        ApiResponse<Channel> CreateChannelWithHttpInfo(Channel? channel = default(Channel?), int operationIndex = 0);
        /// <summary>
        /// Delete the Channel specified by &#39;channel-uri&#39;
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void DeleteChannel(string channelUri, int operationIndex = 0);

        /// <summary>
        /// Delete the Channel specified by &#39;channel-uri&#39;
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteChannelWithHttpInfo(string channelUri, int operationIndex = 0);
        /// <summary>
        /// Retrieve the Channel identified by &#39;channel-uri&#39;
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Channel</returns>
        Channel GetChannel(string channelUri, int operationIndex = 0);

        /// <summary>
        /// Retrieve the Channel identified by &#39;channel-uri&#39;
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Channel</returns>
        ApiResponse<Channel> GetChannelWithHttpInfo(string channelUri, int operationIndex = 0);
        /// <summary>
        /// Retrieve all the channels, subject to security permissions.
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;Channel&gt;</returns>
        List<Channel> GetChannels(int operationIndex = 0);

        /// <summary>
        /// Retrieve all the channels, subject to security permissions.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;Channel&gt;</returns>
        ApiResponse<List<Channel>> GetChannelsWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// Removes security tokens from a channel.
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="requestBody">The security tokens to remove: each token must be specified in full to be removed, i.e., specifying only the username of a UsernamePassword token is insufficient. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void RemoveSecurityTokens(string channelUri, List<Dictionary<String, Object>>? requestBody = default(List<Dictionary<String, Object>>?), int operationIndex = 0);

        /// <summary>
        /// Removes security tokens from a channel.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="requestBody">The security tokens to remove: each token must be specified in full to be removed, i.e., specifying only the username of a UsernamePassword token is insufficient. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> RemoveSecurityTokensWithHttpInfo(string channelUri, List<Dictionary<String, Object>>? requestBody = default(List<Dictionary<String, Object>>?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IChannelManagementApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Adds security tokens to a channel.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="requestBody">The SecurityTokens to add. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task AddSecurityTokensAsync(string channelUri, List<Dictionary<String, Object>>? requestBody = default(List<Dictionary<String, Object>>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Adds security tokens to a channel.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="requestBody">The SecurityTokens to add. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> AddSecurityTokensWithHttpInfoAsync(string channelUri, List<Dictionary<String, Object>>? requestBody = default(List<Dictionary<String, Object>>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Create a new channel with the specified URI path fragment.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channel">The Channel to create (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Channel</returns>
        System.Threading.Tasks.Task<Channel> CreateChannelAsync(Channel? channel = default(Channel?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create a new channel with the specified URI path fragment.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channel">The Channel to create (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Channel)</returns>
        System.Threading.Tasks.Task<ApiResponse<Channel>> CreateChannelWithHttpInfoAsync(Channel? channel = default(Channel?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete the Channel specified by &#39;channel-uri&#39;
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteChannelAsync(string channelUri, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Delete the Channel specified by &#39;channel-uri&#39;
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteChannelWithHttpInfoAsync(string channelUri, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Retrieve the Channel identified by &#39;channel-uri&#39;
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Channel</returns>
        System.Threading.Tasks.Task<Channel> GetChannelAsync(string channelUri, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Retrieve the Channel identified by &#39;channel-uri&#39;
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Channel)</returns>
        System.Threading.Tasks.Task<ApiResponse<Channel>> GetChannelWithHttpInfoAsync(string channelUri, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Retrieve all the channels, subject to security permissions.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Channel&gt;</returns>
        System.Threading.Tasks.Task<List<Channel>> GetChannelsAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Retrieve all the channels, subject to security permissions.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Channel&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Channel>>> GetChannelsWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Removes security tokens from a channel.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="requestBody">The security tokens to remove: each token must be specified in full to be removed, i.e., specifying only the username of a UsernamePassword token is insufficient. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task RemoveSecurityTokensAsync(string channelUri, List<Dictionary<String, Object>>? requestBody = default(List<Dictionary<String, Object>>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Removes security tokens from a channel.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="requestBody">The security tokens to remove: each token must be specified in full to be removed, i.e., specifying only the username of a UsernamePassword token is insufficient. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> RemoveSecurityTokensWithHttpInfoAsync(string channelUri, List<Dictionary<String, Object>>? requestBody = default(List<Dictionary<String, Object>>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IChannelManagementApi : IChannelManagementApiSync, IChannelManagementApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ChannelManagementApi : IChannelManagementApi
    {
        private Isbm2RestClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelManagementApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ChannelManagementApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelManagementApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ChannelManagementApi(string basePath)
        {
            this.Configuration = Isbm2RestClient.Client.Configuration.MergeConfigurations(
                Isbm2RestClient.Client.GlobalConfiguration.Instance,
                new Isbm2RestClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Isbm2RestClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Isbm2RestClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Isbm2RestClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelManagementApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ChannelManagementApi(Isbm2RestClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Isbm2RestClient.Client.Configuration.MergeConfigurations(
                Isbm2RestClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Isbm2RestClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Isbm2RestClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Isbm2RestClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelManagementApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ChannelManagementApi(Isbm2RestClient.Client.ISynchronousClient client, Isbm2RestClient.Client.IAsynchronousClient asyncClient, Isbm2RestClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Isbm2RestClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Isbm2RestClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Isbm2RestClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Isbm2RestClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Isbm2RestClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Adds security tokens to a channel. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="requestBody">The SecurityTokens to add. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void AddSecurityTokens(string channelUri, List<Dictionary<String, Object>>? requestBody = default(List<Dictionary<String, Object>>?), int operationIndex = 0)
        {
            AddSecurityTokensWithHttpInfo(channelUri, requestBody);
        }

        /// <summary>
        /// Adds security tokens to a channel. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="requestBody">The SecurityTokens to add. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Isbm2RestClient.Client.ApiResponse<Object> AddSecurityTokensWithHttpInfo(string channelUri, List<Dictionary<String, Object>>? requestBody = default(List<Dictionary<String, Object>>?), int operationIndex = 0)
        {
            // verify the required parameter 'channelUri' is set
            if (channelUri == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'channelUri' when calling ChannelManagementApi->AddSecurityTokens");
            }

            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "application/xml"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("channel-uri", Isbm2RestClient.Client.ClientUtils.ParameterToString(channelUri)); // path parameter
            localVarRequestOptions.Data = requestBody;

            localVarRequestOptions.Operation = "ChannelManagementApi.AddSecurityTokens";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/channels/{channel-uri}/security-tokens", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AddSecurityTokens", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Adds security tokens to a channel. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="requestBody">The SecurityTokens to add. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task AddSecurityTokensAsync(string channelUri, List<Dictionary<String, Object>>? requestBody = default(List<Dictionary<String, Object>>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await AddSecurityTokensWithHttpInfoAsync(channelUri, requestBody, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Adds security tokens to a channel. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="requestBody">The SecurityTokens to add. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Isbm2RestClient.Client.ApiResponse<Object>> AddSecurityTokensWithHttpInfoAsync(string channelUri, List<Dictionary<String, Object>>? requestBody = default(List<Dictionary<String, Object>>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'channelUri' is set
            if (channelUri == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'channelUri' when calling ChannelManagementApi->AddSecurityTokens");
            }


            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "application/xml"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("channel-uri", Isbm2RestClient.Client.ClientUtils.ParameterToString(channelUri)); // path parameter
            localVarRequestOptions.Data = requestBody;

            localVarRequestOptions.Operation = "ChannelManagementApi.AddSecurityTokens";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/channels/{channel-uri}/security-tokens", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AddSecurityTokens", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new channel with the specified URI path fragment. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channel">The Channel to create (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Channel</returns>
        public Channel CreateChannel(Channel? channel = default(Channel?), int operationIndex = 0)
        {
            Isbm2RestClient.Client.ApiResponse<Channel> localVarResponse = CreateChannelWithHttpInfo(channel);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new channel with the specified URI path fragment. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channel">The Channel to create (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Channel</returns>
        public Isbm2RestClient.Client.ApiResponse<Channel> CreateChannelWithHttpInfo(Channel? channel = default(Channel?), int operationIndex = 0)
        {
            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "application/xml"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = channel;

            localVarRequestOptions.Operation = "ChannelManagementApi.CreateChannel";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Channel>("/channels", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateChannel", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new channel with the specified URI path fragment. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channel">The Channel to create (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Channel</returns>
        public async System.Threading.Tasks.Task<Channel> CreateChannelAsync(Channel? channel = default(Channel?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Isbm2RestClient.Client.ApiResponse<Channel> localVarResponse = await CreateChannelWithHttpInfoAsync(channel, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new channel with the specified URI path fragment. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channel">The Channel to create (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Channel)</returns>
        public async System.Threading.Tasks.Task<Isbm2RestClient.Client.ApiResponse<Channel>> CreateChannelWithHttpInfoAsync(Channel? channel = default(Channel?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "application/xml"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = channel;

            localVarRequestOptions.Operation = "ChannelManagementApi.CreateChannel";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Channel>("/channels", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateChannel", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete the Channel specified by &#39;channel-uri&#39; 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void DeleteChannel(string channelUri, int operationIndex = 0)
        {
            DeleteChannelWithHttpInfo(channelUri);
        }

        /// <summary>
        /// Delete the Channel specified by &#39;channel-uri&#39; 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Isbm2RestClient.Client.ApiResponse<Object> DeleteChannelWithHttpInfo(string channelUri, int operationIndex = 0)
        {
            // verify the required parameter 'channelUri' is set
            if (channelUri == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'channelUri' when calling ChannelManagementApi->DeleteChannel");
            }

            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("channel-uri", Isbm2RestClient.Client.ClientUtils.ParameterToString(channelUri)); // path parameter

            localVarRequestOptions.Operation = "ChannelManagementApi.DeleteChannel";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/channels/{channel-uri}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteChannel", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete the Channel specified by &#39;channel-uri&#39; 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteChannelAsync(string channelUri, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await DeleteChannelWithHttpInfoAsync(channelUri, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Delete the Channel specified by &#39;channel-uri&#39; 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Isbm2RestClient.Client.ApiResponse<Object>> DeleteChannelWithHttpInfoAsync(string channelUri, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'channelUri' is set
            if (channelUri == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'channelUri' when calling ChannelManagementApi->DeleteChannel");
            }


            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("channel-uri", Isbm2RestClient.Client.ClientUtils.ParameterToString(channelUri)); // path parameter

            localVarRequestOptions.Operation = "ChannelManagementApi.DeleteChannel";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/channels/{channel-uri}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteChannel", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve the Channel identified by &#39;channel-uri&#39; 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Channel</returns>
        public Channel GetChannel(string channelUri, int operationIndex = 0)
        {
            Isbm2RestClient.Client.ApiResponse<Channel> localVarResponse = GetChannelWithHttpInfo(channelUri);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve the Channel identified by &#39;channel-uri&#39; 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Channel</returns>
        public Isbm2RestClient.Client.ApiResponse<Channel> GetChannelWithHttpInfo(string channelUri, int operationIndex = 0)
        {
            // verify the required parameter 'channelUri' is set
            if (channelUri == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'channelUri' when calling ChannelManagementApi->GetChannel");
            }

            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("channel-uri", Isbm2RestClient.Client.ClientUtils.ParameterToString(channelUri)); // path parameter

            localVarRequestOptions.Operation = "ChannelManagementApi.GetChannel";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Channel>("/channels/{channel-uri}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetChannel", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve the Channel identified by &#39;channel-uri&#39; 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Channel</returns>
        public async System.Threading.Tasks.Task<Channel> GetChannelAsync(string channelUri, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Isbm2RestClient.Client.ApiResponse<Channel> localVarResponse = await GetChannelWithHttpInfoAsync(channelUri, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve the Channel identified by &#39;channel-uri&#39; 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Channel)</returns>
        public async System.Threading.Tasks.Task<Isbm2RestClient.Client.ApiResponse<Channel>> GetChannelWithHttpInfoAsync(string channelUri, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'channelUri' is set
            if (channelUri == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'channelUri' when calling ChannelManagementApi->GetChannel");
            }


            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("channel-uri", Isbm2RestClient.Client.ClientUtils.ParameterToString(channelUri)); // path parameter

            localVarRequestOptions.Operation = "ChannelManagementApi.GetChannel";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Channel>("/channels/{channel-uri}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetChannel", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve all the channels, subject to security permissions. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;Channel&gt;</returns>
        public List<Channel> GetChannels(int operationIndex = 0)
        {
            Isbm2RestClient.Client.ApiResponse<List<Channel>> localVarResponse = GetChannelsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve all the channels, subject to security permissions. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;Channel&gt;</returns>
        public Isbm2RestClient.Client.ApiResponse<List<Channel>> GetChannelsWithHttpInfo(int operationIndex = 0)
        {
            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "ChannelManagementApi.GetChannels";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<Channel>>("/channels", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetChannels", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve all the channels, subject to security permissions. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Channel&gt;</returns>
        public async System.Threading.Tasks.Task<List<Channel>> GetChannelsAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Isbm2RestClient.Client.ApiResponse<List<Channel>> localVarResponse = await GetChannelsWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve all the channels, subject to security permissions. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Channel&gt;)</returns>
        public async System.Threading.Tasks.Task<Isbm2RestClient.Client.ApiResponse<List<Channel>>> GetChannelsWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "ChannelManagementApi.GetChannels";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<Channel>>("/channels", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetChannels", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Removes security tokens from a channel. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="requestBody">The security tokens to remove: each token must be specified in full to be removed, i.e., specifying only the username of a UsernamePassword token is insufficient. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void RemoveSecurityTokens(string channelUri, List<Dictionary<String, Object>>? requestBody = default(List<Dictionary<String, Object>>?), int operationIndex = 0)
        {
            RemoveSecurityTokensWithHttpInfo(channelUri, requestBody);
        }

        /// <summary>
        /// Removes security tokens from a channel. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="requestBody">The security tokens to remove: each token must be specified in full to be removed, i.e., specifying only the username of a UsernamePassword token is insufficient. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Isbm2RestClient.Client.ApiResponse<Object> RemoveSecurityTokensWithHttpInfo(string channelUri, List<Dictionary<String, Object>>? requestBody = default(List<Dictionary<String, Object>>?), int operationIndex = 0)
        {
            // verify the required parameter 'channelUri' is set
            if (channelUri == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'channelUri' when calling ChannelManagementApi->RemoveSecurityTokens");
            }

            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "application/xml"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("channel-uri", Isbm2RestClient.Client.ClientUtils.ParameterToString(channelUri)); // path parameter
            localVarRequestOptions.Data = requestBody;

            localVarRequestOptions.Operation = "ChannelManagementApi.RemoveSecurityTokens";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/channels/{channel-uri}/security-tokens", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RemoveSecurityTokens", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Removes security tokens from a channel. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="requestBody">The security tokens to remove: each token must be specified in full to be removed, i.e., specifying only the username of a UsernamePassword token is insufficient. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task RemoveSecurityTokensAsync(string channelUri, List<Dictionary<String, Object>>? requestBody = default(List<Dictionary<String, Object>>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await RemoveSecurityTokensWithHttpInfoAsync(channelUri, requestBody, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Removes security tokens from a channel. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="requestBody">The security tokens to remove: each token must be specified in full to be removed, i.e., specifying only the username of a UsernamePassword token is insufficient. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Isbm2RestClient.Client.ApiResponse<Object>> RemoveSecurityTokensWithHttpInfoAsync(string channelUri, List<Dictionary<String, Object>>? requestBody = default(List<Dictionary<String, Object>>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'channelUri' is set
            if (channelUri == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'channelUri' when calling ChannelManagementApi->RemoveSecurityTokens");
            }


            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "application/xml"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("channel-uri", Isbm2RestClient.Client.ClientUtils.ParameterToString(channelUri)); // path parameter
            localVarRequestOptions.Data = requestBody;

            localVarRequestOptions.Operation = "ChannelManagementApi.RemoveSecurityTokens";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/channels/{channel-uri}/security-tokens", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RemoveSecurityTokens", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
