/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Isbm2RestClient.Client;
using Isbm2RestClient.Model;

namespace Isbm2RestClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProviderRequestServiceApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Closes a session.
        /// </summary>
        /// <remarks>
        /// Closes a session of any type. All unexpired messages that have been posted during the session will be expired. ***Note*** This interface is shared by Close Publication Session, Close Subscription Session, Close Provider Request Session, and Close Consumer Request Session.
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void CloseSession(string sessionId, int operationIndex = 0);

        /// <summary>
        /// Closes a session.
        /// </summary>
        /// <remarks>
        /// Closes a session of any type. All unexpired messages that have been posted during the session will be expired. ***Note*** This interface is shared by Close Publication Session, Close Subscription Session, Close Provider Request Session, and Close Consumer Request Session.
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> CloseSessionWithHttpInfo(string sessionId, int operationIndex = 0);
        /// <summary>
        /// Opens a provider request session for a channel for reading requests and posting responses.
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="session">The configuration of the session, i.e., topic filtering, content-filtering, and notication listener address. Only the Topics, ListenerURL, and FilterExpressions are to be provided. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Session</returns>
        Session OpenProviderRequestSession(string channelUri, Session? session = default(Session?), int operationIndex = 0);

        /// <summary>
        /// Opens a provider request session for a channel for reading requests and posting responses.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="session">The configuration of the session, i.e., topic filtering, content-filtering, and notication listener address. Only the Topics, ListenerURL, and FilterExpressions are to be provided. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Session</returns>
        ApiResponse<Session> OpenProviderRequestSessionWithHttpInfo(string channelUri, Session? session = default(Session?), int operationIndex = 0);
        /// <summary>
        /// Posts a response message on a channel.
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the message will/is posted.</param>
        /// <param name="requestId">The identifier of the origianal request for the response.</param>
        /// <param name="message">The Message to be published. Only MessageContent is allowed in the request body. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Message</returns>
        Message PostResponse(string sessionId, string requestId, Message? message = default(Message?), int operationIndex = 0);

        /// <summary>
        /// Posts a response message on a channel.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the message will/is posted.</param>
        /// <param name="requestId">The identifier of the origianal request for the response.</param>
        /// <param name="message">The Message to be published. Only MessageContent is allowed in the request body. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Message</returns>
        ApiResponse<Message> PostResponseWithHttpInfo(string sessionId, string requestId, Message? message = default(Message?), int operationIndex = 0);
        /// <summary>
        /// Returns the first non-expired request message or a previously read expired message that satisfies the session message filters.
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the request message was posted.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Message</returns>
        Message ReadRequest(string sessionId, int operationIndex = 0);

        /// <summary>
        /// Returns the first non-expired request message or a previously read expired message that satisfies the session message filters.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the request message was posted.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Message</returns>
        ApiResponse<Message> ReadRequestWithHttpInfo(string sessionId, int operationIndex = 0);
        /// <summary>
        /// Deletes the first request message, if any, in the session message queue.
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the request message was posted.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void RemoveRequest(string sessionId, int operationIndex = 0);

        /// <summary>
        /// Deletes the first request message, if any, in the session message queue.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the request message was posted.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> RemoveRequestWithHttpInfo(string sessionId, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProviderRequestServiceApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Closes a session.
        /// </summary>
        /// <remarks>
        /// Closes a session of any type. All unexpired messages that have been posted during the session will be expired. ***Note*** This interface is shared by Close Publication Session, Close Subscription Session, Close Provider Request Session, and Close Consumer Request Session.
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task CloseSessionAsync(string sessionId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Closes a session.
        /// </summary>
        /// <remarks>
        /// Closes a session of any type. All unexpired messages that have been posted during the session will be expired. ***Note*** This interface is shared by Close Publication Session, Close Subscription Session, Close Provider Request Session, and Close Consumer Request Session.
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> CloseSessionWithHttpInfoAsync(string sessionId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Opens a provider request session for a channel for reading requests and posting responses.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="session">The configuration of the session, i.e., topic filtering, content-filtering, and notication listener address. Only the Topics, ListenerURL, and FilterExpressions are to be provided. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Session</returns>
        System.Threading.Tasks.Task<Session> OpenProviderRequestSessionAsync(string channelUri, Session? session = default(Session?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Opens a provider request session for a channel for reading requests and posting responses.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="session">The configuration of the session, i.e., topic filtering, content-filtering, and notication listener address. Only the Topics, ListenerURL, and FilterExpressions are to be provided. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Session)</returns>
        System.Threading.Tasks.Task<ApiResponse<Session>> OpenProviderRequestSessionWithHttpInfoAsync(string channelUri, Session? session = default(Session?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Posts a response message on a channel.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the message will/is posted.</param>
        /// <param name="requestId">The identifier of the origianal request for the response.</param>
        /// <param name="message">The Message to be published. Only MessageContent is allowed in the request body. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Message</returns>
        System.Threading.Tasks.Task<Message> PostResponseAsync(string sessionId, string requestId, Message? message = default(Message?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Posts a response message on a channel.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the message will/is posted.</param>
        /// <param name="requestId">The identifier of the origianal request for the response.</param>
        /// <param name="message">The Message to be published. Only MessageContent is allowed in the request body. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Message)</returns>
        System.Threading.Tasks.Task<ApiResponse<Message>> PostResponseWithHttpInfoAsync(string sessionId, string requestId, Message? message = default(Message?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Returns the first non-expired request message or a previously read expired message that satisfies the session message filters.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the request message was posted.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Message</returns>
        System.Threading.Tasks.Task<Message> ReadRequestAsync(string sessionId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Returns the first non-expired request message or a previously read expired message that satisfies the session message filters.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the request message was posted.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Message)</returns>
        System.Threading.Tasks.Task<ApiResponse<Message>> ReadRequestWithHttpInfoAsync(string sessionId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Deletes the first request message, if any, in the session message queue.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the request message was posted.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task RemoveRequestAsync(string sessionId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Deletes the first request message, if any, in the session message queue.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the request message was posted.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> RemoveRequestWithHttpInfoAsync(string sessionId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProviderRequestServiceApi : IProviderRequestServiceApiSync, IProviderRequestServiceApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ProviderRequestServiceApi : IProviderRequestServiceApi
    {
        private Isbm2RestClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ProviderRequestServiceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ProviderRequestServiceApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProviderRequestServiceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ProviderRequestServiceApi(string basePath)
        {
            this.Configuration = Isbm2RestClient.Client.Configuration.MergeConfigurations(
                Isbm2RestClient.Client.GlobalConfiguration.Instance,
                new Isbm2RestClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Isbm2RestClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Isbm2RestClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Isbm2RestClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProviderRequestServiceApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ProviderRequestServiceApi(Isbm2RestClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Isbm2RestClient.Client.Configuration.MergeConfigurations(
                Isbm2RestClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Isbm2RestClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Isbm2RestClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Isbm2RestClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProviderRequestServiceApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ProviderRequestServiceApi(Isbm2RestClient.Client.ISynchronousClient client, Isbm2RestClient.Client.IAsynchronousClient asyncClient, Isbm2RestClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Isbm2RestClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Isbm2RestClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Isbm2RestClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Isbm2RestClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Isbm2RestClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Closes a session. Closes a session of any type. All unexpired messages that have been posted during the session will be expired. ***Note*** This interface is shared by Close Publication Session, Close Subscription Session, Close Provider Request Session, and Close Consumer Request Session.
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void CloseSession(string sessionId, int operationIndex = 0)
        {
            CloseSessionWithHttpInfo(sessionId);
        }

        /// <summary>
        /// Closes a session. Closes a session of any type. All unexpired messages that have been posted during the session will be expired. ***Note*** This interface is shared by Close Publication Session, Close Subscription Session, Close Provider Request Session, and Close Consumer Request Session.
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Isbm2RestClient.Client.ApiResponse<Object> CloseSessionWithHttpInfo(string sessionId, int operationIndex = 0)
        {
            // verify the required parameter 'sessionId' is set
            if (sessionId == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'sessionId' when calling ProviderRequestServiceApi->CloseSession");
            }

            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("session-id", Isbm2RestClient.Client.ClientUtils.ParameterToString(sessionId)); // path parameter

            localVarRequestOptions.Operation = "ProviderRequestServiceApi.CloseSession";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/sessions/{session-id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CloseSession", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Closes a session. Closes a session of any type. All unexpired messages that have been posted during the session will be expired. ***Note*** This interface is shared by Close Publication Session, Close Subscription Session, Close Provider Request Session, and Close Consumer Request Session.
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task CloseSessionAsync(string sessionId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await CloseSessionWithHttpInfoAsync(sessionId, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Closes a session. Closes a session of any type. All unexpired messages that have been posted during the session will be expired. ***Note*** This interface is shared by Close Publication Session, Close Subscription Session, Close Provider Request Session, and Close Consumer Request Session.
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Isbm2RestClient.Client.ApiResponse<Object>> CloseSessionWithHttpInfoAsync(string sessionId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'sessionId' is set
            if (sessionId == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'sessionId' when calling ProviderRequestServiceApi->CloseSession");
            }


            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("session-id", Isbm2RestClient.Client.ClientUtils.ParameterToString(sessionId)); // path parameter

            localVarRequestOptions.Operation = "ProviderRequestServiceApi.CloseSession";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/sessions/{session-id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CloseSession", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Opens a provider request session for a channel for reading requests and posting responses. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="session">The configuration of the session, i.e., topic filtering, content-filtering, and notication listener address. Only the Topics, ListenerURL, and FilterExpressions are to be provided. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Session</returns>
        public Session OpenProviderRequestSession(string channelUri, Session? session = default(Session?), int operationIndex = 0)
        {
            Isbm2RestClient.Client.ApiResponse<Session> localVarResponse = OpenProviderRequestSessionWithHttpInfo(channelUri, session);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Opens a provider request session for a channel for reading requests and posting responses. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="session">The configuration of the session, i.e., topic filtering, content-filtering, and notication listener address. Only the Topics, ListenerURL, and FilterExpressions are to be provided. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Session</returns>
        public Isbm2RestClient.Client.ApiResponse<Session> OpenProviderRequestSessionWithHttpInfo(string channelUri, Session? session = default(Session?), int operationIndex = 0)
        {
            // verify the required parameter 'channelUri' is set
            if (channelUri == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'channelUri' when calling ProviderRequestServiceApi->OpenProviderRequestSession");
            }

            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "application/xml"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("channel-uri", Isbm2RestClient.Client.ClientUtils.ParameterToString(channelUri)); // path parameter
            localVarRequestOptions.Data = session;

            localVarRequestOptions.Operation = "ProviderRequestServiceApi.OpenProviderRequestSession";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Session>("/channels/{channel-uri}/provider-request-sessions", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OpenProviderRequestSession", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Opens a provider request session for a channel for reading requests and posting responses. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="session">The configuration of the session, i.e., topic filtering, content-filtering, and notication listener address. Only the Topics, ListenerURL, and FilterExpressions are to be provided. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Session</returns>
        public async System.Threading.Tasks.Task<Session> OpenProviderRequestSessionAsync(string channelUri, Session? session = default(Session?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Isbm2RestClient.Client.ApiResponse<Session> localVarResponse = await OpenProviderRequestSessionWithHttpInfoAsync(channelUri, session, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Opens a provider request session for a channel for reading requests and posting responses. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelUri">The identifier of the channel to be accessed (retrieved, deleted, modified, etc.)</param>
        /// <param name="session">The configuration of the session, i.e., topic filtering, content-filtering, and notication listener address. Only the Topics, ListenerURL, and FilterExpressions are to be provided. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Session)</returns>
        public async System.Threading.Tasks.Task<Isbm2RestClient.Client.ApiResponse<Session>> OpenProviderRequestSessionWithHttpInfoAsync(string channelUri, Session? session = default(Session?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'channelUri' is set
            if (channelUri == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'channelUri' when calling ProviderRequestServiceApi->OpenProviderRequestSession");
            }


            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "application/xml"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("channel-uri", Isbm2RestClient.Client.ClientUtils.ParameterToString(channelUri)); // path parameter
            localVarRequestOptions.Data = session;

            localVarRequestOptions.Operation = "ProviderRequestServiceApi.OpenProviderRequestSession";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Session>("/channels/{channel-uri}/provider-request-sessions", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OpenProviderRequestSession", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Posts a response message on a channel. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the message will/is posted.</param>
        /// <param name="requestId">The identifier of the origianal request for the response.</param>
        /// <param name="message">The Message to be published. Only MessageContent is allowed in the request body. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Message</returns>
        public Message PostResponse(string sessionId, string requestId, Message? message = default(Message?), int operationIndex = 0)
        {
            Isbm2RestClient.Client.ApiResponse<Message> localVarResponse = PostResponseWithHttpInfo(sessionId, requestId, message);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Posts a response message on a channel. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the message will/is posted.</param>
        /// <param name="requestId">The identifier of the origianal request for the response.</param>
        /// <param name="message">The Message to be published. Only MessageContent is allowed in the request body. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Message</returns>
        public Isbm2RestClient.Client.ApiResponse<Message> PostResponseWithHttpInfo(string sessionId, string requestId, Message? message = default(Message?), int operationIndex = 0)
        {
            // verify the required parameter 'sessionId' is set
            if (sessionId == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'sessionId' when calling ProviderRequestServiceApi->PostResponse");
            }

            // verify the required parameter 'requestId' is set
            if (requestId == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'requestId' when calling ProviderRequestServiceApi->PostResponse");
            }

            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "application/xml"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("session-id", Isbm2RestClient.Client.ClientUtils.ParameterToString(sessionId)); // path parameter
            localVarRequestOptions.PathParameters.Add("request-id", Isbm2RestClient.Client.ClientUtils.ParameterToString(requestId)); // path parameter
            localVarRequestOptions.Data = message;

            localVarRequestOptions.Operation = "ProviderRequestServiceApi.PostResponse";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Message>("/sessions/{session-id}/requests/{request-id}/responses", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostResponse", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Posts a response message on a channel. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the message will/is posted.</param>
        /// <param name="requestId">The identifier of the origianal request for the response.</param>
        /// <param name="message">The Message to be published. Only MessageContent is allowed in the request body. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Message</returns>
        public async System.Threading.Tasks.Task<Message> PostResponseAsync(string sessionId, string requestId, Message? message = default(Message?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Isbm2RestClient.Client.ApiResponse<Message> localVarResponse = await PostResponseWithHttpInfoAsync(sessionId, requestId, message, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Posts a response message on a channel. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the message will/is posted.</param>
        /// <param name="requestId">The identifier of the origianal request for the response.</param>
        /// <param name="message">The Message to be published. Only MessageContent is allowed in the request body. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Message)</returns>
        public async System.Threading.Tasks.Task<Isbm2RestClient.Client.ApiResponse<Message>> PostResponseWithHttpInfoAsync(string sessionId, string requestId, Message? message = default(Message?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'sessionId' is set
            if (sessionId == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'sessionId' when calling ProviderRequestServiceApi->PostResponse");
            }

            // verify the required parameter 'requestId' is set
            if (requestId == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'requestId' when calling ProviderRequestServiceApi->PostResponse");
            }


            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "application/xml"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("session-id", Isbm2RestClient.Client.ClientUtils.ParameterToString(sessionId)); // path parameter
            localVarRequestOptions.PathParameters.Add("request-id", Isbm2RestClient.Client.ClientUtils.ParameterToString(requestId)); // path parameter
            localVarRequestOptions.Data = message;

            localVarRequestOptions.Operation = "ProviderRequestServiceApi.PostResponse";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Message>("/sessions/{session-id}/requests/{request-id}/responses", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostResponse", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Returns the first non-expired request message or a previously read expired message that satisfies the session message filters. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the request message was posted.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Message</returns>
        public Message ReadRequest(string sessionId, int operationIndex = 0)
        {
            Isbm2RestClient.Client.ApiResponse<Message> localVarResponse = ReadRequestWithHttpInfo(sessionId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Returns the first non-expired request message or a previously read expired message that satisfies the session message filters. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the request message was posted.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Message</returns>
        public Isbm2RestClient.Client.ApiResponse<Message> ReadRequestWithHttpInfo(string sessionId, int operationIndex = 0)
        {
            // verify the required parameter 'sessionId' is set
            if (sessionId == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'sessionId' when calling ProviderRequestServiceApi->ReadRequest");
            }

            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("session-id", Isbm2RestClient.Client.ClientUtils.ParameterToString(sessionId)); // path parameter

            localVarRequestOptions.Operation = "ProviderRequestServiceApi.ReadRequest";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Message>("/sessions/{session-id}/request", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReadRequest", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Returns the first non-expired request message or a previously read expired message that satisfies the session message filters. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the request message was posted.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Message</returns>
        public async System.Threading.Tasks.Task<Message> ReadRequestAsync(string sessionId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Isbm2RestClient.Client.ApiResponse<Message> localVarResponse = await ReadRequestWithHttpInfoAsync(sessionId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Returns the first non-expired request message or a previously read expired message that satisfies the session message filters. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the request message was posted.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Message)</returns>
        public async System.Threading.Tasks.Task<Isbm2RestClient.Client.ApiResponse<Message>> ReadRequestWithHttpInfoAsync(string sessionId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'sessionId' is set
            if (sessionId == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'sessionId' when calling ProviderRequestServiceApi->ReadRequest");
            }


            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("session-id", Isbm2RestClient.Client.ClientUtils.ParameterToString(sessionId)); // path parameter

            localVarRequestOptions.Operation = "ProviderRequestServiceApi.ReadRequest";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Message>("/sessions/{session-id}/request", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReadRequest", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Deletes the first request message, if any, in the session message queue. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the request message was posted.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void RemoveRequest(string sessionId, int operationIndex = 0)
        {
            RemoveRequestWithHttpInfo(sessionId);
        }

        /// <summary>
        /// Deletes the first request message, if any, in the session message queue. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the request message was posted.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Isbm2RestClient.Client.ApiResponse<Object> RemoveRequestWithHttpInfo(string sessionId, int operationIndex = 0)
        {
            // verify the required parameter 'sessionId' is set
            if (sessionId == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'sessionId' when calling ProviderRequestServiceApi->RemoveRequest");
            }

            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("session-id", Isbm2RestClient.Client.ClientUtils.ParameterToString(sessionId)); // path parameter

            localVarRequestOptions.Operation = "ProviderRequestServiceApi.RemoveRequest";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/sessions/{session-id}/request", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RemoveRequest", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Deletes the first request message, if any, in the session message queue. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the request message was posted.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task RemoveRequestAsync(string sessionId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await RemoveRequestWithHttpInfoAsync(sessionId, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Deletes the first request message, if any, in the session message queue. 
        /// </summary>
        /// <exception cref="Isbm2RestClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">The identifier of the session to which the request message was posted.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Isbm2RestClient.Client.ApiResponse<Object>> RemoveRequestWithHttpInfoAsync(string sessionId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'sessionId' is set
            if (sessionId == null)
            {
                throw new Isbm2RestClient.Client.ApiException(400, "Missing required parameter 'sessionId' when calling ProviderRequestServiceApi->RemoveRequest");
            }


            Isbm2RestClient.Client.RequestOptions localVarRequestOptions = new Isbm2RestClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = Isbm2RestClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Isbm2RestClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("session-id", Isbm2RestClient.Client.ClientUtils.ParameterToString(sessionId)); // path parameter

            localVarRequestOptions.Operation = "ProviderRequestServiceApi.RemoveRequest";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (username_password) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Isbm2RestClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/sessions/{session-id}/request", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RemoveRequest", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
