/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Isbm2RestClient.Client;
using Isbm2RestClient.Api;
// uncomment below to import models
//using Isbm2RestClient.Model;

namespace Isbm2RestClient.Test.Api
{
    /// <summary>
    ///  Class for testing ConfigurationDiscoveryServiceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ConfigurationDiscoveryServiceApiTests : IDisposable
    {
        private ConfigurationDiscoveryServiceApi instance;

        public ConfigurationDiscoveryServiceApiTests()
        {
            instance = new ConfigurationDiscoveryServiceApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConfigurationDiscoveryServiceApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ConfigurationDiscoveryServiceApi
            //Assert.IsType<ConfigurationDiscoveryServiceApi>(instance);
        }

        /// <summary>
        /// Test GetSecurityDetails
        /// </summary>
        [Fact]
        public void GetSecurityDetailsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetSecurityDetails();
            //Assert.IsType<SecurityDetails>(response);
        }

        /// <summary>
        /// Test GetSupportedOperations
        /// </summary>
        [Fact]
        public void GetSupportedOperationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetSupportedOperations();
            //Assert.IsType<SupportedOperations>(response);
        }
    }
}
