/*
 * ISBM 2.0
 *
 * An OpenAPI specification for the ISBM 2.0 RESTful interface.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@mimosa.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Isbm2RestClient.Client;
using Isbm2RestClient.Api;
// uncomment below to import models
//using Isbm2RestClient.Model;

namespace Isbm2RestClient.Test.Api
{
    /// <summary>
    ///  Class for testing ProviderRequestServiceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProviderRequestServiceApiTests : IDisposable
    {
        private ProviderRequestServiceApi instance;

        public ProviderRequestServiceApiTests()
        {
            instance = new ProviderRequestServiceApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProviderRequestServiceApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ProviderRequestServiceApi
            //Assert.IsType<ProviderRequestServiceApi>(instance);
        }

        /// <summary>
        /// Test CloseSession
        /// </summary>
        [Fact]
        public void CloseSessionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string sessionId = null;
            //instance.CloseSession(sessionId);
        }

        /// <summary>
        /// Test OpenProviderRequestSession
        /// </summary>
        [Fact]
        public void OpenProviderRequestSessionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string channelUri = null;
            //Session? session = null;
            //var response = instance.OpenProviderRequestSession(channelUri, session);
            //Assert.IsType<Session>(response);
        }

        /// <summary>
        /// Test PostResponse
        /// </summary>
        [Fact]
        public void PostResponseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string sessionId = null;
            //string requestId = null;
            //Message? message = null;
            //var response = instance.PostResponse(sessionId, requestId, message);
            //Assert.IsType<Message>(response);
        }

        /// <summary>
        /// Test ReadRequest
        /// </summary>
        [Fact]
        public void ReadRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string sessionId = null;
            //var response = instance.ReadRequest(sessionId);
            //Assert.IsType<Message>(response);
        }

        /// <summary>
        /// Test RemoveRequest
        /// </summary>
        [Fact]
        public void RemoveRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string sessionId = null;
            //instance.RemoveRequest(sessionId);
        }
    }
}
